package GUI;

/**
 *
 * @author Harim
 */
public class PythCalcGUI extends javax.swing.JFrame {

    /**
     * Creates new form PythCalcGUI
     */
    public PythCalcGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Answer = new javax.swing.ButtonGroup();
        Side = new javax.swing.ButtonGroup();
        sideLength = new javax.swing.JLabel();
        entryOne = new javax.swing.JTextField();
        entryTwo = new javax.swing.JTextField();
        Leg = new javax.swing.JRadioButton();
        Hypotenuse = new javax.swing.JRadioButton();
        Actual = new javax.swing.JRadioButton();
        Rounded = new javax.swing.JRadioButton();
        AnswerLabel = new javax.swing.JLabel();
        SideLabel = new javax.swing.JLabel();
        Calculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pyth Calc");

        sideLength.setText("Side Length");
        sideLength.setToolTipText("");

        Side.add(Leg);
        Leg.setText("Leg");
        Leg.setToolTipText("");

        Side.add(Hypotenuse);
        Hypotenuse.setText("Hypotenuse");

        Answer.add(Actual);
        Actual.setText("Actual");

        Answer.add(Rounded);
        Rounded.setText("Rounded");

        AnswerLabel.setText("Form of answer:");

        SideLabel.setText("Missing side:");

        Calculate.setText("Calculate");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entryOne, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Leg)
                            .addComponent(Hypotenuse)
                            .addComponent(SideLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rounded)
                            .addComponent(AnswerLabel)
                            .addComponent(entryTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Actual))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Calculate)
                            .addComponent(sideLength, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(sideLength)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnswerLabel)
                    .addComponent(SideLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Actual)
                    .addComponent(Leg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rounded)
                    .addComponent(Hypotenuse))
                .addGap(18, 18, 18)
                .addComponent(Calculate)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        AnswerLabel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        double numOne = testInput(entryOne.getText());
        double numTwo = testInput(entryTwo.getText());
        if (numOne <= 0 || numTwo <= 0) {
            return;
        }
        if (Leg.isSelected()) {
            legCalc (numOne, numTwo);
        } else if (Hypotenuse.isSelected()) {
            hypoCalc (numOne, numTwo);
        }
    }//GEN-LAST:event_CalculateActionPerformed

    public double testInput (String input) {
        double Dinput;
        try {
            Dinput = Double.parseDouble(input);
        } catch (Exception e) {
            Dinput = -1.0;
        }
        if (Dinput <= 0) {
            sideLength.setText ("ERROR");
        }
        return Dinput;
    }
    
    public void printTotal (double total) {
        if (Actual.isSelected()) {
            sideLength.setText("Side length: Square Root of ("+Double.toString(total)+")");
        } else if (Rounded.isSelected()) {
            total = Math.sqrt(total);
            sideLength.setText("Side length: "+Double.toString(total));
        }
    }
    
    public void legCalc (double numOne, double numTwo) {
        double sqOne = numOne * numOne;
        double sqTwo = numTwo * numTwo;
        double total;
        if (sqOne < sqTwo) {
            total = sqTwo - sqOne;
        } else if (sqTwo < sqOne) {
            total = sqOne - sqTwo;
        } else {
            sideLength.setText("ERROR");
            return;
        }
        printTotal (total);
    }
    
    public void hypoCalc (double numOne, double numTwo) {
        double sqOne = numOne * numOne;
        double sqTwo = numTwo * numTwo;
        double total = sqOne + sqTwo;
        printTotal (total);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PythCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PythCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PythCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PythCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PythCalcGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Actual;
    private javax.swing.ButtonGroup Answer;
    private javax.swing.JLabel AnswerLabel;
    private javax.swing.JButton Calculate;
    private javax.swing.JRadioButton Hypotenuse;
    private javax.swing.JRadioButton Leg;
    private javax.swing.JRadioButton Rounded;
    private javax.swing.ButtonGroup Side;
    private javax.swing.JLabel SideLabel;
    private javax.swing.JTextField entryOne;
    private javax.swing.JTextField entryTwo;
    private javax.swing.JLabel sideLength;
    // End of variables declaration//GEN-END:variables
}
